sonar.projectKey=SonarQubeTest
sonar.organization=hocnguyen0605

# ???ng d?n ??n mã ngu?n
sonar.sources=.
# Lo?i b? các th? m?c không c?n test (ví d?: th? vi?n, test data)
sonar.exclusions=**/node_modules/**, **/migrations/**

